### ISSUE TITLE
能不能放出编译好的插件？

### ISSUE THREAD

**Issue by Aurora1468** [icrons/Campus-network#1]
回学校后switch连不上网，自己尝试编译了一下但因为没有openwrt编译的经验所以进行起来有些困难。能否分享一下编译好的插件？万分感激

**Comment by icrons** [comment]
> 回学校后switch连不上网，自己尝试编译了一下但因为没有openwrt编译的经验所以进行起来有些困难。能否分享一下编译好的插件？万分感激

仓库里面.bin文件就是编译好的，直接对应路由器型号刷固件就行了，如果没有你路由器的对应固件，也给我发下路由器配置信息，帮你编译也可以。

**Comment by Aurora1468** [comment]
> > 回学校后switch连不上网，自己尝试编译了一下但因为没有openwrt编译的经验所以进行起来有些困难。能否分享一下编译好的插件？万分感激
> 
> 仓库里面.bin文件就是编译好的，直接对应路由器型号刷固件就行了，如果没有你路由器的对应固件，也给我发下路由器配置信息，帮你编译也可以。

我用的是斐讯N1盒子，所以没办法像一般路由器那样刷入固件，可不可以从已编译好的固件中提取出插件呢？

**Comment by icrons** [comment]
> > > 回学校后switch连不上网，自己尝试编译了一下但因为没有openwrt编译的经验所以进行起来有些困难。能否分享一下编译好的插件？万分感激
> > 
> > 
> > 仓库里面.bin文件就是编译好的，直接对应路由器型号刷固件就行了，如果没有你路由器的对应固件，也给我发下路由器配置信息，帮你编译也可以。
> 
> 我用的是斐讯N1盒子，所以没办法像一般路由器那样刷入固件，可不可以从已编译好的固件中提取出插件呢？

n1可以刷固件的吧，破解插件好像opkg不了吧，我没试过，我都是直接编译的。

**Comment by Aurora1468** [comment]
> > > > 回学校后switch连不上网，自己尝试编译了一下但因为没有openwrt编译的经验所以进行起来有些困难。能否分享一下编译好的插件？万分感激
> > > 
> > > 
> > > 仓库里面.bin文件就是编译好的，直接对应路由器型号刷固件就行了，如果没有你路由器的对应固件，也给我发下路由器配置信息，帮你编译也可以。
> > 
> > 
> > 我用的是斐讯N1盒子，所以没办法像一般路由器那样刷入固件，可不可以从已编译好的固件中提取出插件呢？
> 
> n1可以刷固件的吧，破解插件好像opkg不了吧，我没试过，我都是直接编译的。

没有办法单独编译插件嘛？如果不行我再想其他办法吧

**Comment by icrons** [comment]
> > > > > 回学校后switch连不上网，自己尝试编译了一下但因为没有openwrt编译的经验所以进行起来有些困难。能否分享一下编译好的插件？万分感激
> > > > 
> > > > 
> > > > 仓库里面.bin文件就是编译好的，直接对应路由器型号刷固件就行了，如果没有你路由器的对应固件，也给我发下路由器配置信息，帮你编译也可以。
> > > 
> > > 
> > > 我用的是斐讯N1盒子，所以没办法像一般路由器那样刷入固件，可不可以从已编译好的固件中提取出插件呢？
> > 
> > 
> > n1可以刷固件的吧，破解插件好像opkg不了吧，我没试过，我都是直接编译的。
> 
> 没有办法单独编译插件嘛？如果不行我再想其他办法吧

我没有试过，您自己研究下吧

**Comment by shenyunet** [comment]
我有编译好的，可以加我QQ2448004638
