### ISSUE TITLE
MiAC2100

### ISSUE THREAD

**Issue by NEUMUKI** [icrons/Campus-network#2]
请问大佬可以出一个小米AC2100的吗，卑微萌新求助

**Comment by icrons** [comment]
> 请问大佬可以出一个小米AC2100的吗，卑微萌新求助

下载:https://gocos.lanzoui.com/irq0Vtpnp0h 密码:29hj

**Comment by NEUMUKI** [comment]
谢谢大佬！！

Icrons ***@***.***> 于 2021年9月7日周二 下午12:15写道：
